# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ADiqMlPMPjgTDdOUdcWZqzfFISCplEFp/model.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ADiqMlPMPjgTDdOUdcWZqzfFISCplEFp/model.proto',
  package='ADiqMlPMPjgTDdOUdcWZqzfFISCplEFp',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n,ADiqMlPMPjgTDdOUdcWZqzfFISCplEFp/model.proto\x12 ADiqMlPMPjgTDdOUdcWZqzfFISCplEFp\"L\n\x0bImageTagSet\x12=\n\tImageTags\x18\x01 \x03(\x0b\x32*.ADiqMlPMPjgTDdOUdcWZqzfFISCplEFp.ImageTag\"5\n\x08ImageTag\x12\r\n\x05image\x18\x01 \x01(\x03\x12\x0b\n\x03tag\x18\x02 \x01(\t\x12\r\n\x05score\x18\x03 \x01(\x01\x32q\n\x05Model\x12h\n\x08\x63lassify\x12-.ADiqMlPMPjgTDdOUdcWZqzfFISCplEFp.ImageTagSet\x1a-.ADiqMlPMPjgTDdOUdcWZqzfFISCplEFp.ImageTagSetb\x06proto3')
)




_IMAGETAGSET = _descriptor.Descriptor(
  name='ImageTagSet',
  full_name='ADiqMlPMPjgTDdOUdcWZqzfFISCplEFp.ImageTagSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ImageTags', full_name='ADiqMlPMPjgTDdOUdcWZqzfFISCplEFp.ImageTagSet.ImageTags', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=158,
)


_IMAGETAG = _descriptor.Descriptor(
  name='ImageTag',
  full_name='ADiqMlPMPjgTDdOUdcWZqzfFISCplEFp.ImageTag',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='ADiqMlPMPjgTDdOUdcWZqzfFISCplEFp.ImageTag.image', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tag', full_name='ADiqMlPMPjgTDdOUdcWZqzfFISCplEFp.ImageTag.tag', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='score', full_name='ADiqMlPMPjgTDdOUdcWZqzfFISCplEFp.ImageTag.score', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=213,
)

_IMAGETAGSET.fields_by_name['ImageTags'].message_type = _IMAGETAG
DESCRIPTOR.message_types_by_name['ImageTagSet'] = _IMAGETAGSET
DESCRIPTOR.message_types_by_name['ImageTag'] = _IMAGETAG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImageTagSet = _reflection.GeneratedProtocolMessageType('ImageTagSet', (_message.Message,), dict(
  DESCRIPTOR = _IMAGETAGSET,
  __module__ = 'ADiqMlPMPjgTDdOUdcWZqzfFISCplEFp.model_pb2'
  # @@protoc_insertion_point(class_scope:ADiqMlPMPjgTDdOUdcWZqzfFISCplEFp.ImageTagSet)
  ))
_sym_db.RegisterMessage(ImageTagSet)

ImageTag = _reflection.GeneratedProtocolMessageType('ImageTag', (_message.Message,), dict(
  DESCRIPTOR = _IMAGETAG,
  __module__ = 'ADiqMlPMPjgTDdOUdcWZqzfFISCplEFp.model_pb2'
  # @@protoc_insertion_point(class_scope:ADiqMlPMPjgTDdOUdcWZqzfFISCplEFp.ImageTag)
  ))
_sym_db.RegisterMessage(ImageTag)



_MODEL = _descriptor.ServiceDescriptor(
  name='Model',
  full_name='ADiqMlPMPjgTDdOUdcWZqzfFISCplEFp.Model',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=215,
  serialized_end=328,
  methods=[
  _descriptor.MethodDescriptor(
    name='classify',
    full_name='ADiqMlPMPjgTDdOUdcWZqzfFISCplEFp.Model.classify',
    index=0,
    containing_service=None,
    input_type=_IMAGETAGSET,
    output_type=_IMAGETAGSET,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MODEL)

DESCRIPTOR.services_by_name['Model'] = _MODEL

# @@protoc_insertion_point(module_scope)
